# Generated by Django 5.1.2 on 2024-10-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='birthday',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='users',
            name='firstName',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='users',
            name='lastName',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='users',
            name='Password',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='users',
            name='Username',
            field=models.CharField(default='', max_length=15),
        ),
    ]
