# Generated by Django 5.1.2 on 2024-10-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_users_birthday_users_email_users_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='birthday',
            new_name='Birthday',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='firstName',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='lastName',
            new_name='LastName',
        ),
        migrations.AddField(
            model_name='users',
            name='Gender',
            field=models.CharField(default='', max_length=1),
        ),
    ]
