# Generated by Django 5.1.2 on 2024-12-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_users_address_users_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='city',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='users',
            name='state',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
