# Generated by Django 5.1.2 on 2024-12-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_users_city_users_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
    ]
