# Generated by Django 5.1.2 on 2024-12-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_users_is_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
