# Generated by Django 5.1.2 on 2024-12-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_users_access_token_users_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='account_number',
            field=models.CharField(blank=True, max_length=48),
        ),
        migrations.AddField(
            model_name='users',
            name='amount',
            field=models.CharField(blank=True, max_length=48),
        ),
        migrations.AddField(
            model_name='users',
            name='currency',
            field=models.CharField(blank=True, max_length=48),
        ),
        migrations.AddField(
            model_name='users',
            name='routing_number',
            field=models.CharField(blank=True, max_length=48),
        ),
        migrations.AddField(
            model_name='users',
            name='transaction_date',
            field=models.CharField(blank=True, max_length=48),
        ),
        migrations.AddField(
            model_name='users',
            name='transaction_description',
            field=models.CharField(blank=True, max_length=48),
        ),
    ]
