# Generated by Django 5.1.2 on 2024-10-30 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_alter_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator]),
        ),
    ]
