# Generated by Django 5.1.2 on 2024-11-11 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_alter_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='users',
            name='Gender',
            field=models.CharField(default='', max_length=8),
        ),
    ]
