# Generated by Django 5.1.2 on 2024-11-11 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0011_alter_users_email_alter_users_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Email',
            field=models.EmailField(default='', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
