# Generated by Django 5.1.2 on 2024-11-11 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0012_alter_users_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='Gender',
        ),
    ]
